import DOMPurify from 'dompurify'
import MarkdownIt from 'markdown-it'
import katex from 'katex'
import hljs from 'highlight.js/lib/core'
import bash from 'highlight.js/lib/languages/bash'
import c from 'highlight.js/lib/languages/c'
import cpp from 'highlight.js/lib/languages/cpp'
import go from 'highlight.js/lib/languages/go'
import java from 'highlight.js/lib/languages/java'
import javascript from 'highlight.js/lib/languages/javascript'
import json from 'highlight.js/lib/languages/json'
import markdownLanguage from 'highlight.js/lib/languages/markdown'
import python from 'highlight.js/lib/languages/python'
import rust from 'highlight.js/lib/languages/rust'
import sql from 'highlight.js/lib/languages/sql'
import typescript from 'highlight.js/lib/languages/typescript'
import xml from 'highlight.js/lib/languages/xml'
import yaml from 'highlight.js/lib/languages/yaml'

hljs.registerLanguage('bash', bash)
hljs.registerLanguage('c', c)
hljs.registerLanguage('cpp', cpp)
hljs.registerLanguage('go', go)
hljs.registerLanguage('java', java)
hljs.registerLanguage('javascript', javascript)
hljs.registerLanguage('json', json)
hljs.registerLanguage('markdown', markdownLanguage)
hljs.registerLanguage('python', python)
hljs.registerLanguage('rust', rust)
hljs.registerLanguage('sql', sql)
hljs.registerLanguage('typescript', typescript)
hljs.registerLanguage('xml', xml)
hljs.registerLanguage('yaml', yaml)

const LANGUAGE_LABELS: Record<string, string> = {
  bash: 'Bash',
  c: 'C',
  cpp: 'C++',
  go: 'Go',
  java: 'Java',
  javascript: 'JavaScript',
  js: 'JavaScript',
  json: 'JSON',
  markdown: 'Markdown',
  md: 'Markdown',
  python: 'Python',
  py: 'Python',
  rust: 'Rust',
  rs: 'Rust',
  sql: 'SQL',
  typescript: 'TypeScript',
  ts: 'TypeScript',
  xml: 'XML',
  html: 'HTML',
  yaml: 'YAML',
  yml: 'YAML',
}

function escapeHtml(source: string): string {
  return source
    .replace(/&/g, '&amp;')
    .replace(/</g, '&lt;')
    .replace(/>/g, '&gt;')
    .replace(/"/g, '&quot;')
}

function escapeAttribute(source: string): string {
  return escapeHtml(source).replace(/'/g, '&#39;')
}

function highlightCode(code: string, language: string): string {
  const normalizedLanguage = language.trim().toLowerCase()

  if (normalizedLanguage && hljs.getLanguage(normalizedLanguage)) {
    try {
      return hljs.highlight(code, {
        language: normalizedLanguage,
        ignoreIllegals: true,
      }).value
    } catch {
      return escapeHtml(code)
    }
  }

  try {
    return hljs.highlightAuto(code).value
  } catch {
    return escapeHtml(code)
  }
}

function formatLanguageLabel(language: string): string {
  const normalized = language.trim().toLowerCase()
  if (!normalized) return 'Code'
  return LANGUAGE_LABELS[normalized] ?? normalized.toUpperCase()
}

const plainMarkdown = new MarkdownIt({
  html: false,
  linkify: true,
  breaks: true,
})

const markdown = new MarkdownIt({
  html: false,
  linkify: true,
  breaks: true,
})

markdown.renderer.rules.fence = (tokens, index): string => {
  const token = tokens[index]
  if (!token) return ''

  const info = token.info ? token.info.trim().split(/\s+/)[0] ?? '' : ''
  const highlighted = highlightCode(token.content, info)
  const safeLanguage = escapeHtml(info)
  const languageClass = safeLanguage ? ` language-${safeLanguage}` : ''
  const languageLabel = escapeHtml(formatLanguageLabel(info))
  const copyCode = escapeAttribute(token.content)

  return [
    '<div class="markdown-code-block">',
    '<div class="markdown-code-block__header">',
    `<span class="markdown-code-block__title">${languageLabel}</span>`,
    `<button class="markdown-code-block__copy" type="button" aria-label="Copy code" data-code="${copyCode}">`,
    '<svg viewBox="0 0 24 24" aria-hidden="true" focusable="false">',
    '<rect x="8" y="8" width="10" height="12" rx="2"></rect>',
    '<path d="M6 16H5a2 2 0 0 1-2-2V6a2 2 0 0 1 2-2h8a2 2 0 0 1 2 2v1"></path>',
    '</svg>',
    '</button>',
    '</div>',
    `<pre><code class="hljs${languageClass}">${highlighted}</code></pre>`,
    '</div>',
  ].join('')
}

// MathML tags generated by KaTeX for accessibility; stripped by DOMPurify by default.
const MATHML_TAGS = [
  'math',
  'semantics',
  'annotation',
  'mrow',
  'mi',
  'mo',
  'mn',
  'mtext',
  'msup',
  'msub',
  'mover',
  'munder',
  'mfrac',
  'msqrt',
  'mtable',
  'mtr',
  'mtd',
  'munderover',
  'mspace',
  'mpadded',
  'mphantom',
  'menclose',
  'mstyle',
  'merror',
]

const MATHML_ATTR = [
  'xmlns',
  'mathvariant',
  'mathsize',
  'displaystyle',
  'scriptlevel',
  'linethickness',
  'columnspan',
  'rowspan',
  'stretchy',
  'fence',
  'separator',
  'lspace',
  'rspace',
  'movablelimits',
  'accent',
  'accentunder',
  'align',
  'depth',
  'height',
  'width',
]

// Placeholder format uses only alphanumeric characters to avoid triggering
// markdown-it emphasis/escape rules. Curly braces are safe literal text.
const placeholderRe = /\{KTX(\d+)\}/g

function renderMath(
  text: string,
  mathBlocks: string[],
): string {
  // Block math: \[...\] — used by many LLMs
  text = text.replace(/\\\[([\s\S]*?)\\\]/g, (_full, math: string) => {
    const id = mathBlocks.length
    mathBlocks.push(
      katex.renderToString(math.trim(), {
        displayMode: true,
        throwOnError: false,
      }),
    )
    return `{KTX${id}}`
  })

  // Inline math: \(...\)
  text = text.replace(/\\\(([^\n]*?)\\\)/g, (_full, math: string) => {
    const id = mathBlocks.length
    mathBlocks.push(
      katex.renderToString(math, {
        displayMode: false,
        throwOnError: false,
      }),
    )
    return `{KTX${id}}`
  })

  // Block math: $$...$$
  text = text.replace(/\$\$([\s\S]*?)\$\$/g, (_full, math: string) => {
    const id = mathBlocks.length
    mathBlocks.push(
      katex.renderToString(math.trim(), {
        displayMode: true,
        throwOnError: false,
      }),
    )
    return `{KTX${id}}`
  })

  // Inline math: $...$ — single-line, not preceded by \
  text = text.replace(/(?<!\\)\$([^\n$]+?)(?<!\\)\$/g, (_full, math: string) => {
    const id = mathBlocks.length
    mathBlocks.push(
      katex.renderToString(math, {
        displayMode: false,
        throwOnError: false,
      }),
    )
    return `{KTX${id}}`
  })

  return text
}

export function renderMarkdown(source: string): string {
  const mathBlocks: string[] = []

  // Split by fenced code blocks so math delimiters inside code are ignored.
  const parts = source.split(/(```[\s\S]*?```)/g)
  const processed = parts
    .map((part, i) => {
      // Odd indices are fenced code blocks — leave untouched.
      if (i % 2 === 1) return part
      return renderMath(part, mathBlocks)
    })
    .join('')

  let html = markdown.render(processed)

  html = DOMPurify.sanitize(html, {
    ADD_TAGS: MATHML_TAGS,
    ADD_ATTR: [...MATHML_ATTR, 'class', 'type', 'aria-label', 'data-code', 'viewBox', 'focusable'],
  })

  // Swap KaTeX HTML back after sanitisation so it renders as real elements.
  html = html.replace(placeholderRe, (_full, id: string) => {
    return mathBlocks[Number(id)] ?? ''
  })

  return html
}

export function renderMarkdownPlain(source: string): string {
  const mathBlocks: string[] = []

  const parts = source.split(/(```[\s\S]*?```)/g)
  const processed = parts
    .map((part, i) => {
      if (i % 2 === 1) return part
      return renderMath(part, mathBlocks)
    })
    .join('')

  let html = plainMarkdown.render(processed)

  html = DOMPurify.sanitize(html, {
    ADD_TAGS: MATHML_TAGS,
    ADD_ATTR: [...MATHML_ATTR, 'class', 'type'],
  })

  html = html.replace(placeholderRe, (_full, id: string) => {
    return mathBlocks[Number(id)] ?? ''
  })

  return html
}
