import DOMPurify from 'dompurify'
import MarkdownIt from 'markdown-it'
import katex from 'katex'

const markdown = new MarkdownIt({
  html: false,
  linkify: true,
  breaks: true,
})

// MathML tags generated by KaTeX for accessibility; stripped by DOMPurify by default.
const MATHML_TAGS = [
  'math',
  'semantics',
  'annotation',
  'mrow',
  'mi',
  'mo',
  'mn',
  'mtext',
  'msup',
  'msub',
  'mover',
  'munder',
  'mfrac',
  'msqrt',
  'mtable',
  'mtr',
  'mtd',
  'munderover',
  'mspace',
  'mpadded',
  'mphantom',
  'menclose',
  'mstyle',
  'merror',
]

const MATHML_ATTR = [
  'xmlns',
  'mathvariant',
  'mathsize',
  'displaystyle',
  'scriptlevel',
  'linethickness',
  'columnspan',
  'rowspan',
  'stretchy',
  'fence',
  'separator',
  'lspace',
  'rspace',
  'movablelimits',
  'accent',
  'accentunder',
  'align',
  'depth',
  'height',
  'width',
]

// Placeholder format uses only alphanumeric characters to avoid triggering
// markdown-it emphasis/escape rules. Curly braces are safe literal text.
const placeholderRe = /\{KTX(\d+)\}/g

/**
 * Render $...$ and $$...$$ LaTeX math with KaTeX, replacing each formula
 * with a `{KTXn}` placeholder. The placeholder survives markdown-it and
 * DOMPurify unchanged, so we can swap the real KaTeX HTML back in last.
 */
function renderMath(
  text: string,
  mathBlocks: string[],
): string {
  // Block math: $$...$$
  text = text.replace(/\$\$([\s\S]*?)\$\$/g, (_full, math: string) => {
    const id = mathBlocks.length
    mathBlocks.push(
      katex.renderToString(math.trim(), {
        displayMode: true,
        throwOnError: false,
      }),
    )
    return `{KTX${id}}`
  })

  // Inline math: $...$ — single-line, not preceded by \
  text = text.replace(/(?<!\\)\$([^\n$]+?)(?<!\\)\$/g, (_full, math: string) => {
    const id = mathBlocks.length
    mathBlocks.push(
      katex.renderToString(math, {
        displayMode: false,
        throwOnError: false,
      }),
    )
    return `{KTX${id}}`
  })

  return text
}

export function renderMarkdown(source: string): string {
  const mathBlocks: string[] = []

  // Split by fenced code blocks so math delimiters inside code are ignored.
  const parts = source.split(/(```[\s\S]*?```)/g)
  const processed = parts
    .map((part, i) => {
      // Odd indices are fenced code blocks — leave untouched.
      if (i % 2 === 1) return part
      return renderMath(part, mathBlocks)
    })
    .join('')

  let html = markdown.render(processed)

  html = DOMPurify.sanitize(html, {
    ADD_TAGS: MATHML_TAGS,
    ADD_ATTR: MATHML_ATTR,
  })

  // Swap KaTeX HTML back after sanitisation so it renders as real elements.
  html = html.replace(placeholderRe, (_full, id: string) => {
    return mathBlocks[Number(id)] ?? ''
  })

  return html
}
